import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    // next-env.d.ts is generated by Next.js on every build; do not lint it.
    ignores: [".next/**", "node_modules/**", "playwright-report/**", "test-results/**", "next-env.d.ts"],
  },

  ...compat.extends("next/core-web-vitals", "next/typescript"),

  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "no-console": ["warn", { allow: ["info", "warn", "error"] }],
      // Leading underscore marks a parameter kept for the signature but not
      // used yet — common in the scaffolded modules.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  {
    // createAdminClient() bypasses RLS. It must never be reachable from code
    // that renders in the browser — see docs/02-architecture.md §2.4.
    files: ["src/components/**", "src/app/**/page.tsx", "src/app/**/layout.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/lib/supabase/admin", "@/lib/supabase/admin"],
              message:
                "createAdminClient() bypasses RLS. Use it only in src/app/api/** or scripts/**.",
            },
          ],
        },
      ],
    },
  },
];

export default config;
