/**
 * Machine-readable version of the file-ownership matrix in AGENTS.md §3.
 *
 * OWNER: PM. Agents do not edit this file — it is what checks them.
 *
 * Keep in sync with AGENTS.md §3. If the two disagree, this file wins,
 * because it is the one that actually runs.
 *
 * Patterns: `**` matches any depth, `*` matches within one segment.
 * A path with no `*` must match exactly.
 */

/**
 * Shared ground.
 *
 * Task status and blockers: every agent updates its own row.
 *
 * Unit tests and their fixtures: whoever writes the code writes its tests.
 * QA-BOT owns end-to-end tests, not the unit layer — the matrix used to give
 * it all of tests/**, which flagged DEV-INT for adding tests to the Drive
 * client it had just written.
 */
export const COMMON = [
  "tasks/TASK-INDEX.md",
  "tasks/BLOCKERS.md",
  // Every agent needs to add a dependency sooner or later, and only DEV-OPS
  // owned the file that lists them. The part worth guarding is the scripts
  // block — the gates live there — and verify-ownership.mjs guards that
  // separately, for everyone but DEV-OPS and PM.
  "package.json",
  "package-lock.json",
  "tests/unit/**",
  "tests/fixtures/**",
];

/**
 * Only the PM writes these. They are the rules and the gates; an agent that
 * can edit its own examiner is not being examined.
 */
export const PROTECTED = [
  "AGENTS.md",
  "GEMINI.md",
  "scripts/ownership.mjs",
  "scripts/verify-ownership.mjs",
  "scripts/verify-db.mjs",
  "scripts/verify-build.mjs",
  "scripts/verify-prod.mjs",
  "scripts/verify-wired.mjs",
];

export const OWNERSHIP = {
  ARCH: [
    "db/schema.sql",
    "db/migrations/**",
    "src/types/domain.ts",
    // Hình dạng phản hồi của mọi route — cùng họ với docs/04-api-spec.md, nên
    // thuộc ARCH. Trước BB-148 tệp này KHÔNG có chủ, và verify:own chặn đúng
    // lúc SEC-ARCH cần sửa nó để thôi ghi lỗi ra "[object Object]".
    "src/lib/api-response.ts",
    "docs/**",
  ],
  "DEV-BE": [
    "db/seed.sql",
    "db/migrations/**",
    "src/app/api/**",
    "src/lib/selection/**",
    "src/lib/supabase/**",
    "scripts/db-seed.mjs",
    "scripts/db-push.mjs",
  ],
  // src/app/api/admin/reports/** nằm ở DEV-FE chứ không ở DEV-BE, cùng lý lẽ
  // với db/migrations/** ghi bên dưới: tách ra là tạo một lần bàn giao.
  //
  // Một đường báo cáo chỉ đọc, sinh ra để nuôi đúng một màn hình, mà chủ màn
  // hình không được viết thì phải chờ người khác — và chỗ nguy hiểm nhất của
  // đường đó (lọc theo chi nhánh, vì service_role đi vòng qua RLS) nằm đúng
  // ngay chỗ bàn giao.
  //
  // Cái giữ an toàn ở đây KHÔNG phải ai sở hữu tệp, mà là phép thử: mỗi đường
  // báo cáo phải có một ca chứng minh nhân viên chi nhánh A không thấy dữ liệu
  // chi nhánh B, và ca đó phải đỏ khi gỡ bộ lọc ra. Xem
  // tests/unit/loi-dong-bo-report-api.test.ts và over-quota.
  //
  // PM chốt ngày 14.09.2026 sau khi BB-129 vấp phải ranh giới này.
  "DEV-FE": [
    "src/app/(customer)/**",
    "src/app/(admin)/**",
    "src/app/api/admin/reports/**",
    "src/components/features/**",
    "src/lib/utils/**",
  ],
  "DEV-UI": [
    "src/components/ui/**",
    "src/styles/**",
    "src/i18n/**",
  ],
  "DEV-INT": [
    "src/lib/drive/**",
    "src/lib/lark/**",
    "src/app/api/img/**",
    "scripts/sync-drive.ts",
    "scripts/sync-lark-catalog.mjs",
    "scripts/sync-lark-contracts.mjs",
    "scripts/sync-lark-hauky.mjs",
  ],
  // db/migrations/** on purpose: the agent that fixes a policy has to be able
  // to ship it to production. Splitting those two created a handoff, and the
  // handoff dropped the accountant-photo fix. verify:own now refuses a change
  // to policies.sql that arrives without a migration beside it.
  // src/app/api/auth/** belongs here, not with the rest of the API. Without it
  // SEC-ARCH had to hide the customer auth route inside the (auth) page group
  // to stay in its lane, which works only because route groups do not appear
  // in the URL. Two homes for API routes is how one of them gets forgotten.
  "SEC-ARCH": [
    "db/policies.sql",
    "src/app/api/auth/**",
    "db/migrations/**",
    "docs/12-security.md",
    "src/lib/auth/**",
    "src/middleware.ts",
    "src/app/(auth)/**",
    "tests/security/**",
    "vitest.config.ts",
  ],
  "DEV-OPS": [
    ".github/**",
    "vercel.json",
    "eslint.config.mjs",
    "next.config.ts",
    "postcss.config.mjs",
    "tsconfig.json",
    "scripts/backup.mjs",
    "docs/11-deployment.md",
  ],
  "QA-BOT": [
    "tests/**",
    "playwright.config.ts",
  ],
  DESIGNER: [
    "public/brand/**",
  ],
  PM: ["**"],
};

/** Turns a glob into a regex anchored at both ends. */
function toRegExp(pattern) {
  let out = "";
  for (let i = 0; i < pattern.length; i++) {
    const c = pattern[i];
    if (c === "*") {
      if (pattern[i + 1] === "*") {
        if (pattern[i + 2] === "/") {
          // `a/**/b` matches `a/b` too, so the whole segment is optional.
          out += "(?:.*/)?";
          i += 2;
        } else {
          out += ".*";
          i += 1;
        }
      } else {
        out += "[^/]*";
      }
    } else if (".+^${}()|[]\\".includes(c)) {
      // Route groups like (admin) put regex metacharacters in real paths.
      out += "\\" + c;
    } else {
      out += c;
    }
  }
  return new RegExp(`^${out}$`);
}

export function matches(pattern, file) {
  return toRegExp(pattern).test(file);
}

/** Every agent allowed to write `file`, ignoring COMMON and PROTECTED. */
export function ownersOf(file) {
  return Object.entries(OWNERSHIP)
    .filter(([name, patterns]) => name !== "PM" && patterns.some((p) => matches(p, file)))
    .map(([name]) => name);
}

export function isCommon(file) {
  return COMMON.some((p) => matches(p, file));
}

export function isProtected(file) {
  return PROTECTED.some((p) => matches(p, file));
}

export const AGENT_NAMES = Object.keys(OWNERSHIP);
